name: mobile_ebook_reader
description: A mobile ebook reading app with WooCommerce integration

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^3.0.1
  
  # State Management
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  
  # PDF & EPUB Reading
  flutter_pdfview: ^1.3.2
  epub_kitty: ^0.0.5
  syncfusion_flutter_pdfviewer: ^23.2.7
  
  # File Management
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  dio_downloader: ^1.0.0
  
  # UI Components
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.2.4
  flutter_spinkit: ^5.2.0
  lottie: ^2.7.0
  
  # Storage & Database
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication & Security
  crypto: ^3.0.3
  jwt_decoder: ^2.0.1
  
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700